"""
Real in-app playoff bracket engine — closes the competitive audit's
#2 confirmed structural gap (2026-09): the playoff bracket has never
actually been generated by this app. It's read from a live, separate
ESPN league via the same private, unofficial `espn_api` library the
draft/roster/lineup pivot was explicitly built to eliminate —
`matchups.is_playoff` itself is set by that ESPN sync (week number vs.
ESPN's own reported reg_season_count), not computed here. If that
shadow ESPN league is ever abandoned or mismanaged, this app has no
playoffs at all — an operational continuity risk to its own real
season, not just a competitive-feature gap.

This module generates the bracket TREE (app/queries/leagues.py's
migration for playoff_bracket_matchups: round/slot/seed/winner) and the
real per-week `matchups` rows for whichever rounds are currently
playable, seeded from this app's own get_standings — no ESPN read
anywhere in this file.

Deliberately scoped to a single-elimination bracket with NO byes —
playoff_team_count must be a power of 2 (2, 4, 8, ...). This league's
real settings (the commissioner's own ESPN screenshot): 4 playoff
teams, 2 weeks per matchup — semifinals then a final, 4 playoff weeks
total. A non-power-of-2 count (byes for top seeds) is a real, known
gap — see UnsupportedPlayoffTeamCountError — deliberately out of scope
for this first version, matching the audit's own "even a simple
version is far better than none" scoping standard.

2026-10: the whole bracket is now described by bracket_spec — every
game's code (SF1, F, 3RD, C1..C8), which bracket it's in, where each
team comes from (a seed, or the winner/loser of an earlier game) and
what place each result earns. Alongside the winners' bracket it adds a
3rd-place game and, for this league's shape (4 playoff teams, 8 more),
ESPN's consolation ladder: every team plays for a real final place,
down to the Toilet Bowl (GmC8, 11th vs 12th). Generation, resolution,
the projection and the clients' what-if engine all read the same spec.

Two entry points:

- generate_playoff_bracket: called once, when the regular season is
  over and the commissioner is ready (e.g. a POST /admin/playoffs/
  generate trigger) — seeds round 1 from get_standings, creates every
  round's bracket_matchups skeleton row (later rounds start with both
  teams NULL), and writes round 1's real matchups rows immediately
  since both its teams are already known.

- resolve_ready_playoff_matchups: called after every real scoring
  compute (wired into app/scheduler.py's weekly-compute job, right
  after weekly_stats.compute_and_store_week) — finds every bracket
  node whose two teams are known, isn't resolved yet, and whose linked
  matchups rows are all fully scored; sums each side's real points
  across weeks_per_matchup weeks, sets the winner (ties go to the
  better seed — team_a, by construction — a real, disclosed tiebreak
  rather than an unhandled edge case), and — if that winner completes
  the two inputs some later round needs — fills in that round's teams
  and writes ITS real matchups rows too. Idempotent: a node already
  resolved, or not yet ready, is simply skipped on every call.
"""
import math

from app.config import DEFAULT_LEAGUE_ID
from app.domain.playoff_exceptions import (
    PlayoffAlreadyGeneratedError,
    PlayoffTeamCountUnknownError,
    RegularSeasonNotStartedError,
    UnsupportedPlayoffTeamCountError,
)
from app.queries.league import get_playoff_settings, get_standings


def _is_power_of_two(n: int) -> bool:
    return n >= 2 and (n & (n - 1)) == 0


async def _infer_start_week(conn, season: int, league_id: int) -> int:
    """One week after this season's own last real regular-season week
    (matchups.is_playoff = FALSE) — real data already in this app's own
    DB, not an ESPN read. Used only when the commissioner hasn't set an
    explicit start_week (league_playoff_settings)."""
    last_regular_week = await conn.fetchval(
        "SELECT MAX(week) FROM matchups WHERE season = $1 AND league_id = $2 AND is_playoff = FALSE",
        season, league_id,
    )
    if last_regular_week is None:
        raise RegularSeasonNotStartedError(
            f"No regular-season matchups exist yet for season {season} — nothing to build a playoff schedule after"
        )
    return last_regular_week + 1


# The commissioner's punishment for losing the Toilet Bowl. "TBD" until
# the league decides (2026-10).
TOILET_BOWL_PUNISHMENT = "TBD"


def bracket_spec(team_count: int, total_teams: int) -> list[dict]:
    """Every game in the bracket, in play order. Each game:
    code, bracket ("winners" | "consolation"), round, slot, label,
    sources — two of {"kind": "seed", "seed": n} or {"kind": "winner" |
    "loser", "code": c} — and places: [winner's place, loser's place]
    for a game that decides final places, else None.

    Winners: a single-elimination bracket for team_count (a power of 2)
    plus a 3rd-place game in the final round. Consolation: ESPN's
    two-round ladder for exactly 8 more teams when the playoffs are two
    rounds long (this league): GmC1-4 pair adjacent seeds, then GmC5
    (5th), GmC6 (7th), GmC7 (9th) and GmC8 — the Toilet Bowl, for 11th
    and 12th. Any other shape gets no consolation games."""
    rounds = int(math.log2(team_count))
    games: list[dict] = []

    def code_for(r: int, slot: int) -> str:
        if r == rounds:
            return "F"
        if r == rounds - 1:
            return f"SF{slot + 1}"
        return f"R{r}-{slot + 1}"

    def label_for(r: int, slot: int) -> str:
        if r == rounds:
            return "Championship"
        if r == rounds - 1:
            return f"Semifinal {slot + 1}"
        return f"Round {r} · Game {slot + 1}"

    for r in range(1, rounds + 1):
        for slot in range(team_count // (2 ** r)):
            if r == 1:
                sources = [{"kind": "seed", "seed": slot + 1}, {"kind": "seed", "seed": team_count - slot}]
            else:
                sources = [
                    {"kind": "winner", "code": code_for(r - 1, 2 * slot)},
                    {"kind": "winner", "code": code_for(r - 1, 2 * slot + 1)},
                ]
            games.append({
                "code": code_for(r, slot), "bracket": "winners", "round": r, "slot": slot,
                "label": label_for(r, slot), "sources": sources, "places": [1, 2] if r == rounds else None,
            })
    if rounds >= 2:
        games.append({
            "code": "3RD", "bracket": "winners", "round": rounds, "slot": 1, "label": "3rd Place",
            "sources": [{"kind": "loser", "code": "SF1"}, {"kind": "loser", "code": "SF2"}], "places": [3, 4],
        })

    if rounds == 2 and total_teams - team_count == 8:
        base = team_count  # seeds team_count+1 .. team_count+8
        seed = lambda n: {"kind": "seed", "seed": base + n}  # noqa: E731
        w = lambda c: {"kind": "winner", "code": c}  # noqa: E731
        lo = lambda c: {"kind": "loser", "code": c}  # noqa: E731
        ladder = [
            ("C1", 1, 0, "GmC1", [seed(1), seed(2)], None),
            ("C2", 1, 1, "GmC2", [seed(3), seed(4)], None),
            ("C3", 1, 2, "GmC3", [seed(5), seed(6)], None),
            ("C4", 1, 3, "GmC4", [seed(7), seed(8)], None),
            ("C5", 2, 0, f"GmC5 · {base + 1}th Place", [w("C1"), w("C2")], [base + 1, base + 2]),
            ("C6", 2, 1, f"GmC6 · {base + 3}th Place", [lo("C1"), w("C3")], [base + 3, base + 4]),
            ("C7", 2, 2, f"GmC7 · {base + 5}th Place", [lo("C2"), w("C4")], [base + 5, base + 6]),
            ("C8", 2, 3, "Toilet Bowl", [lo("C3"), lo("C4")], [base + 7, base + 8]),
        ]
        for code, r, slot, label, sources, places in ladder:
            games.append({
                "code": code, "bracket": "consolation", "round": r, "slot": slot, "label": label,
                "sources": sources, "places": places,
            })
    return games


async def _bracket_shape(conn, season: int, league_id: int) -> tuple[dict, int, list]:
    settings = await get_playoff_settings(conn, season, league_id)
    team_count = settings["playoff_team_count"]
    if team_count is None:
        raise PlayoffTeamCountUnknownError(
            "No playoff_team_count is set for this season and no prior season's real bracket to infer one from — "
            "set it via PUT /league/playoff-settings first"
        )
    if not _is_power_of_two(team_count):
        raise UnsupportedPlayoffTeamCountError(
            f"playoff_team_count={team_count} isn't a power of 2 — this bracket engine doesn't support byes yet"
        )
    standings = await get_standings(conn, season, league_id)
    return settings, team_count, standings


async def generate_playoff_bracket(conn, season: int, league_id: int = DEFAULT_LEAGUE_ID) -> list[dict]:
    existing = await conn.fetchval(
        "SELECT 1 FROM playoff_bracket_matchups WHERE season = $1 AND league_id = $2 LIMIT 1",
        season, league_id,
    )
    if existing:
        raise PlayoffAlreadyGeneratedError(f"A playoff bracket already exists for season {season}")

    settings, team_count, standings = await _bracket_shape(conn, season, league_id)
    weeks_per_matchup = settings["weeks_per_matchup"]
    start_week = settings["start_week"] or await _infer_start_week(conn, season, league_id)
    if len(standings) < team_count:
        raise PlayoffTeamCountUnknownError(
            f"playoff_team_count={team_count} but only {len(standings)} teams have real standings this season"
        )
    seeds = [dict(row) for row in standings]

    created_nodes = []
    async with conn.transaction():
        # Every game's row exists up front (round-1 games seeded, later
        # games' teams NULL until their sources resolve), so the
        # bracket's whole shape is visible immediately.
        for game in bracket_spec(team_count, len(seeds)):
            team_a_id = team_a_seed = team_b_id = team_b_seed = None
            if all(src["kind"] == "seed" for src in game["sources"]):
                (sa, sb) = (src["seed"] for src in game["sources"])
                team_a_id, team_a_seed = seeds[sa - 1]["team_id"], sa
                team_b_id, team_b_seed = seeds[sb - 1]["team_id"], sb
            node_id = await conn.fetchval(
                """
                INSERT INTO playoff_bracket_matchups
                    (season, league_id, round, slot, code, bracket, team_a_id, team_a_seed, team_b_id, team_b_seed)
                VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
                RETURNING id
                """,
                season, league_id, game["round"], game["slot"], game["code"], game["bracket"],
                team_a_id, team_a_seed, team_b_id, team_b_seed,
            )
            if team_a_id is not None:
                await _create_matchup_weeks(
                    conn, season, league_id, node_id, team_a_id, team_b_id,
                    start_week + (game["round"] - 1) * weeks_per_matchup, weeks_per_matchup,
                )
            created_nodes.append({
                "id": node_id, "round": game["round"], "slot": game["slot"], "code": game["code"],
                "bracket": game["bracket"],
                "team_a_id": team_a_id, "team_a_seed": team_a_seed,
                "team_b_id": team_b_id, "team_b_seed": team_b_seed,
            })
    return created_nodes


async def _create_matchup_weeks(
    conn, season: int, league_id: int, bracket_matchup_id: int,
    team_a_id: int, team_b_id: int, first_week: int, weeks_per_matchup: int,
) -> None:
    for offset in range(weeks_per_matchup):
        await conn.execute(
            """
            INSERT INTO matchups
                (season, week, home_team_id, away_team_id, is_playoff, league_id, playoff_bracket_matchup_id)
            VALUES ($1, $2, $3, $4, TRUE, $5, $6)
            """,
            season, first_week + offset, team_a_id, team_b_id, league_id, bracket_matchup_id,
        )


async def resolve_ready_playoff_matchups(conn, season: int, league_id: int = DEFAULT_LEAGUE_ID) -> list[dict]:
    """Decides every game whose weeks are all scored, then fills each
    game fed by its winner or loser (bracket_spec's sources), writing
    that game's matchup weeks once both its teams are known."""
    settings = await get_playoff_settings(conn, season, league_id)
    weeks_per_matchup = settings["weeks_per_matchup"]
    team_count = settings["playoff_team_count"]
    total_teams = await conn.fetchval(
        "SELECT COUNT(*) FROM teams_by_season WHERE season = $1 AND league_id = $2", season, league_id
    )
    spec = bracket_spec(team_count, total_teams) if team_count and _is_power_of_two(team_count) else []

    pending = await conn.fetch(
        """
        SELECT id, round, slot, code, team_a_id, team_a_seed, team_b_id, team_b_seed
        FROM playoff_bracket_matchups
        WHERE season = $1 AND league_id = $2 AND winner_team_id IS NULL
          AND team_a_id IS NOT NULL AND team_b_id IS NOT NULL
        ORDER BY round, slot
        """,
        season, league_id,
    )

    resolved = []
    for node in pending:
        scores = await conn.fetch(
            "SELECT home_score, away_score FROM matchups WHERE playoff_bracket_matchup_id = $1",
            node["id"],
        )
        if len(scores) < weeks_per_matchup or any(r["home_score"] is None or r["away_score"] is None for r in scores):
            continue  # not every real week has a score in yet

        team_a_total = sum(r["home_score"] for r in scores)
        team_b_total = sum(r["away_score"] for r in scores)
        # A tie over an aggregate of real fantasy scores is very unlikely
        # but possible — the better seed wins it, a real disclosed
        # tiebreak rather than an unhandled state.
        if team_a_total != team_b_total:
            a_wins = team_a_total > team_b_total
        else:
            a_wins = (node["team_a_seed"] or 99) <= (node["team_b_seed"] or 99)
        winner = (node["team_a_id"], node["team_a_seed"]) if a_wins else (node["team_b_id"], node["team_b_seed"])
        loser = (node["team_b_id"], node["team_b_seed"]) if a_wins else (node["team_a_id"], node["team_a_seed"])

        async with conn.transaction():
            await conn.execute(
                "UPDATE playoff_bracket_matchups SET winner_team_id = $1 WHERE id = $2", winner[0], node["id"],
            )
            resolved.append({
                "id": node["id"], "round": node["round"], "slot": node["slot"], "code": node["code"],
                "winner_team_id": winner[0],
            })
            for game in spec:
                for side, src in enumerate(game["sources"]):
                    if src.get("code") != node["code"]:
                        continue
                    team_id, seed = winner if src["kind"] == "winner" else loser
                    await _fill_and_schedule(
                        conn, season, league_id, settings, game, side, team_id, seed, weeks_per_matchup,
                    )
    return resolved


async def _fill_and_schedule(conn, season, league_id, settings, game, side, team_id, seed, weeks_per_matchup):
    team_col, seed_col = ("team_a_id", "team_a_seed") if side == 0 else ("team_b_id", "team_b_seed")
    target = await conn.fetchrow(
        f"UPDATE playoff_bracket_matchups SET {team_col} = $1, {seed_col} = $2 "
        "WHERE season = $3 AND league_id = $4 AND code = $5 "
        "RETURNING id, round, team_a_id, team_b_id",
        team_id, seed, season, league_id, game["code"],
    )
    if target is None or target["team_a_id"] is None or target["team_b_id"] is None:
        return
    # Both sides known: this game's real weeks can be written now.
    start_week = settings["start_week"] or await _infer_start_week(conn, season, league_id)
    await _create_matchup_weeks(
        conn, season, league_id, target["id"], target["team_a_id"], target["team_b_id"],
        start_week + (target["round"] - 1) * weeks_per_matchup, weeks_per_matchup,
    )


async def get_bracket_view(conn, season: int, league_id: int = DEFAULT_LEAGUE_ID) -> list[dict]:
    """Read-only display shape for the bracket — team names (not just
    ids) and each node's real aggregate score so far (summed across
    however many of its weeks_per_matchup weeks are already scored),
    for a frontend bracket view. Empty list before generate_playoff_
    bracket has ever run for this season."""
    rows = await conn.fetch(
        """
        SELECT b.id, b.round, b.slot, b.code, b.bracket,
               b.team_a_id, ta.team_name AS team_a_name, b.team_a_seed,
               b.team_b_id, tb.team_name AS team_b_name, b.team_b_seed,
               b.winner_team_id, tw.team_name AS winner_team_name,
               s.team_a_score, s.team_b_score, s.weeks_played
        FROM playoff_bracket_matchups b
        LEFT JOIN teams_by_season ta ON ta.id = b.team_a_id
        LEFT JOIN teams_by_season tb ON tb.id = b.team_b_id
        LEFT JOIN teams_by_season tw ON tw.id = b.winner_team_id
        LEFT JOIN LATERAL (
            SELECT SUM(m.home_score) AS team_a_score, SUM(m.away_score) AS team_b_score, COUNT(*) AS weeks_played
            FROM matchups m WHERE m.playoff_bracket_matchup_id = b.id
        ) s ON TRUE
        WHERE b.season = $1 AND b.league_id = $2
        ORDER BY b.round, b.slot
        """,
        season, league_id,
    )
    return [dict(r) for r in rows]


async def get_projected_playoff_picture(conn, season: int, league_id: int = DEFAULT_LEAGUE_ID) -> list[dict] | None:
    """"If the season ended today" — round 1's real seeded matchups,
    recomputed live from get_standings on every call (no DB write, no
    bracket_matchups row, no real matchups row) rather than generated
    once. Purely a projection: deliberately stops at round 1 rather
    than guessing who'd win to fabricate a full bracket — same "a
    preview, not a guaranteed clinch" restraint the standings page's
    own playoff-line divider already applies, and the same reasoning
    get_standings' own tiebreak-shallow ordering already carries here
    (wins DESC, points_for DESC, no head-to-head/points-against
    tiebreak — a real limitation this projection inherits, not a new
    one it introduces).

    Returns None once a real bracket has actually been generated for
    this season (get_bracket_view is authoritative from that point on
    — showing a hypothetical alongside a real one would just be
    confusing) or when there isn't yet enough real data to project
    from (playoff_team_count unknown, not enough teams, or not a
    supported power-of-2 count)."""
    has_real_bracket = await conn.fetchval(
        "SELECT 1 FROM playoff_bracket_matchups WHERE season = $1 AND league_id = $2 LIMIT 1", season, league_id,
    )
    if has_real_bracket:
        return None

    settings = await get_playoff_settings(conn, season, league_id)
    team_count = settings["playoff_team_count"]
    if team_count is None or not _is_power_of_two(team_count):
        return None

    standings = await get_standings(conn, season, league_id)
    if len(standings) < team_count:
        return None
    seeds = [dict(row) for row in standings[:team_count]]

    return [
        {
            "slot": i,
            "team_a_id": seeds[i]["team_id"], "team_a_name": seeds[i]["team_name"], "team_a_seed": i + 1,
            "team_b_id": seeds[team_count - 1 - i]["team_id"], "team_b_name": seeds[team_count - 1 - i]["team_name"],
            "team_b_seed": team_count - i,
        }
        for i in range(team_count // 2)
    ]


async def get_playoff_world(conn, season: int, league_id: int = DEFAULT_LEAGUE_ID) -> dict | None:
    """Everything the bracket screens and the what-if engine need to
    rebuild the season on the device (2026-10): the teams, every
    regular-season game (with whether it's final), the bracket spec,
    and — once a real bracket exists — each game's real teams, scores
    and winner. Standings and seeds are computed on the client the same
    way get_standings orders them (wins, ties as half, then points for)
    so flipping a game reseeds instantly. None when the league has no
    playoff settings or a shape this engine can't build."""
    from app.providers.nfl_scoreboard import get_week_scoreboard, is_week_final

    settings = await get_playoff_settings(conn, season, league_id)
    team_count = settings["playoff_team_count"]
    if team_count is None or not _is_power_of_two(team_count):
        return None

    teams = await conn.fetch(
        """
        SELECT t.id AS team_id, t.team_name, o.owner_id, o.logo_url,
               COALESCE(o.goes_by, split_part(o.display_name, ' ', 1)) AS name
        FROM teams_by_season t JOIN owners o ON o.owner_id = t.owner_id
        WHERE t.season = $1 AND t.league_id = $2
        ORDER BY t.id
        """,
        season, league_id,
    )
    if len(teams) < team_count:
        return None

    current_week = await conn.fetchval("SELECT current_week FROM league_state WHERE season = $1", season)
    current_final = False
    if current_week is not None:
        current_final = is_week_final(await get_week_scoreboard(week=current_week, year=season))
    games = await conn.fetch(
        """
        SELECT id, week, home_team_id, away_team_id, home_score, away_score FROM matchups
        WHERE season = $1 AND league_id = $2 AND is_playoff = FALSE
        ORDER BY week, id
        """,
        season, league_id,
    )

    def played(g) -> bool:
        if g["home_score"] is None or g["away_score"] is None or (g["home_score"] == 0 and g["away_score"] == 0):
            return False
        if current_week is not None and g["week"] == current_week:
            return current_final
        return current_week is None or g["week"] < current_week

    schedule = [
        {
            "id": g["id"], "week": g["week"], "home_team_id": g["home_team_id"], "away_team_id": g["away_team_id"],
            "home_score": float(g["home_score"] or 0), "away_score": float(g["away_score"] or 0), "played": played(g),
        }
        for g in games
    ]
    last_regular_week = max((g["week"] for g in games), default=None)
    start_week = settings["start_week"] or ((last_regular_week or 0) + 1)
    weeks_per_matchup = settings["weeks_per_matchup"]

    live = {n["code"]: n for n in await get_bracket_view(conn, season, league_id) if n.get("code")}
    spec_games = []
    for game in bracket_spec(team_count, len(teams)):
        first = start_week + (game["round"] - 1) * weeks_per_matchup
        node = live.get(game["code"])
        spec_games.append({
            **game,
            "weeks": list(range(first, first + weeks_per_matchup)),
            "toilet_bowl": game["code"] == "C8",
            "team_a_id": node["team_a_id"] if node else None,
            "team_b_id": node["team_b_id"] if node else None,
            "team_a_seed": node["team_a_seed"] if node else None,
            "team_b_seed": node["team_b_seed"] if node else None,
            "score_a": float(node["team_a_score"]) if node and node["team_a_score"] is not None else None,
            "score_b": float(node["team_b_score"]) if node and node["team_b_score"] is not None else None,
            "winner_team_id": node["winner_team_id"] if node else None,
        })

    return {
        "season": season,
        "status": "live" if live else "projected",
        "playoff_team_count": team_count,
        "weeks_per_matchup": weeks_per_matchup,
        "start_week": start_week,
        "regular_season_last_week": last_regular_week,
        "toilet_bowl_punishment": TOILET_BOWL_PUNISHMENT,
        "teams": [dict(t) for t in teams],
        "schedule": schedule,
        "games": spec_games,
    }

