"""
Real in-app playoff bracket engine — closes the competitive audit's
#2 confirmed structural gap (2026-09): the playoff bracket has never
actually been generated by this app. It's read from a live, separate
ESPN league via the same private, unofficial `espn_api` library the
draft/roster/lineup pivot was explicitly built to eliminate —
`matchups.is_playoff` itself is set by that ESPN sync (week number vs.
ESPN's own reported reg_season_count), not computed here. If that
shadow ESPN league is ever abandoned or mismanaged, this app has no
playoffs at all — an operational continuity risk to its own real
season, not just a competitive-feature gap.

This module generates the bracket TREE (app/queries/leagues.py's
migration for playoff_bracket_matchups: round/slot/seed/winner) and the
real per-week `matchups` rows for whichever rounds are currently
playable, seeded from this app's own get_standings — no ESPN read
anywhere in this file.

Deliberately scoped to a single-elimination bracket with NO byes —
playoff_team_count must be a power of 2 (2, 4, 8, ...). This league's
real settings (the commissioner's own ESPN screenshot): 4 playoff
teams, 2 weeks per matchup — semifinals then a final, 4 playoff weeks
total. A non-power-of-2 count (byes for top seeds) is a real, known
gap — see UnsupportedPlayoffTeamCountError — deliberately out of scope
for this first version, matching the audit's own "even a simple
version is far better than none" scoping standard.

Two entry points:

- generate_playoff_bracket: called once, when the regular season is
  over and the commissioner is ready (e.g. a POST /admin/playoffs/
  generate trigger) — seeds round 1 from get_standings, creates every
  round's bracket_matchups skeleton row (later rounds start with both
  teams NULL), and writes round 1's real matchups rows immediately
  since both its teams are already known.

- resolve_ready_playoff_matchups: called after every real scoring
  compute (wired into app/scheduler.py's weekly-compute job, right
  after weekly_stats.compute_and_store_week) — finds every bracket
  node whose two teams are known, isn't resolved yet, and whose linked
  matchups rows are all fully scored; sums each side's real points
  across weeks_per_matchup weeks, sets the winner (ties go to the
  better seed — team_a, by construction — a real, disclosed tiebreak
  rather than an unhandled edge case), and — if that winner completes
  the two inputs some later round needs — fills in that round's teams
  and writes ITS real matchups rows too. Idempotent: a node already
  resolved, or not yet ready, is simply skipped on every call.
"""
import math

from app.config import DEFAULT_LEAGUE_ID
from app.domain.playoff_exceptions import (
    PlayoffAlreadyGeneratedError,
    PlayoffTeamCountUnknownError,
    RegularSeasonNotStartedError,
    UnsupportedPlayoffTeamCountError,
)
from app.queries.league import get_playoff_settings, get_standings


def _is_power_of_two(n: int) -> bool:
    return n >= 2 and (n & (n - 1)) == 0


async def _infer_start_week(conn, season: int, league_id: int) -> int:
    """One week after this season's own last real regular-season week
    (matchups.is_playoff = FALSE) — real data already in this app's own
    DB, not an ESPN read. Used only when the commissioner hasn't set an
    explicit start_week (league_playoff_settings)."""
    last_regular_week = await conn.fetchval(
        "SELECT MAX(week) FROM matchups WHERE season = $1 AND league_id = $2 AND is_playoff = FALSE",
        season, league_id,
    )
    if last_regular_week is None:
        raise RegularSeasonNotStartedError(
            f"No regular-season matchups exist yet for season {season} — nothing to build a playoff schedule after"
        )
    return last_regular_week + 1


async def generate_playoff_bracket(conn, season: int, league_id: int = DEFAULT_LEAGUE_ID) -> list[dict]:
    existing = await conn.fetchval(
        "SELECT 1 FROM playoff_bracket_matchups WHERE season = $1 AND league_id = $2 LIMIT 1",
        season, league_id,
    )
    if existing:
        raise PlayoffAlreadyGeneratedError(f"A playoff bracket already exists for season {season}")

    settings = await get_playoff_settings(conn, season, league_id)
    team_count = settings["playoff_team_count"]
    if team_count is None:
        raise PlayoffTeamCountUnknownError(
            "No playoff_team_count is set for this season and no prior season's real bracket to infer one from — "
            "set it via PUT /league/playoff-settings first"
        )
    if not _is_power_of_two(team_count):
        raise UnsupportedPlayoffTeamCountError(
            f"playoff_team_count={team_count} isn't a power of 2 — this bracket engine doesn't support byes yet"
        )

    weeks_per_matchup = settings["weeks_per_matchup"]
    start_week = settings["start_week"] or await _infer_start_week(conn, season, league_id)
    rounds = int(math.log2(team_count))

    standings = await get_standings(conn, season, league_id)
    if len(standings) < team_count:
        raise PlayoffTeamCountUnknownError(
            f"playoff_team_count={team_count} but only {len(standings)} teams have real standings this season"
        )
    seeds = [dict(row) for row in standings[:team_count]]

    created_nodes = []
    async with conn.transaction():
        # Every round's skeleton row exists up front (round 1 seeded,
        # later rounds' teams NULL until their inputs resolve) so the
        # bracket's real shape — how many rounds, who could meet whom —
        # is visible immediately, not built up piecemeal as rounds
        # complete.
        node_id_by_round_slot: dict[tuple[int, int], int] = {}
        for round_num in range(1, rounds + 1):
            slots_this_round = team_count // (2 ** round_num)
            for slot in range(slots_this_round):
                team_a_id = team_a_seed = team_b_id = team_b_seed = None
                if round_num == 1:
                    seed_a = seeds[slot]
                    seed_b = seeds[team_count - 1 - slot]
                    team_a_id, team_a_seed = seed_a["team_id"], slot + 1
                    team_b_id, team_b_seed = seed_b["team_id"], team_count - slot
                node_id = await conn.fetchval(
                    """
                    INSERT INTO playoff_bracket_matchups
                        (season, league_id, round, slot, team_a_id, team_a_seed, team_b_id, team_b_seed)
                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
                    RETURNING id
                    """,
                    season, league_id, round_num, slot, team_a_id, team_a_seed, team_b_id, team_b_seed,
                )
                node_id_by_round_slot[(round_num, slot)] = node_id
                created_nodes.append({
                    "id": node_id, "round": round_num, "slot": slot,
                    "team_a_id": team_a_id, "team_a_seed": team_a_seed,
                    "team_b_id": team_b_id, "team_b_seed": team_b_seed,
                })

        # Round 1 is the only round with both teams known right now —
        # write its real per-week matchups immediately. Later rounds get
        # theirs from resolve_ready_playoff_matchups once their inputs
        # are known.
        round_1_slots = team_count // 2
        for slot in range(round_1_slots):
            node_id = node_id_by_round_slot[(1, slot)]
            seed_a = seeds[slot]
            seed_b = seeds[team_count - 1 - slot]
            await _create_matchup_weeks(
                conn, season, league_id, node_id, seed_a["team_id"], seed_b["team_id"],
                start_week, weeks_per_matchup,
            )

    return created_nodes


async def _create_matchup_weeks(
    conn, season: int, league_id: int, bracket_matchup_id: int,
    team_a_id: int, team_b_id: int, first_week: int, weeks_per_matchup: int,
) -> None:
    for offset in range(weeks_per_matchup):
        await conn.execute(
            """
            INSERT INTO matchups
                (season, week, home_team_id, away_team_id, is_playoff, league_id, playoff_bracket_matchup_id)
            VALUES ($1, $2, $3, $4, TRUE, $5, $6)
            """,
            season, first_week + offset, team_a_id, team_b_id, league_id, bracket_matchup_id,
        )


async def resolve_ready_playoff_matchups(conn, season: int, league_id: int = DEFAULT_LEAGUE_ID) -> list[dict]:
    settings = await get_playoff_settings(conn, season, league_id)
    weeks_per_matchup = settings["weeks_per_matchup"]

    pending = await conn.fetch(
        """
        SELECT id, round, slot, team_a_id, team_b_id
        FROM playoff_bracket_matchups
        WHERE season = $1 AND league_id = $2 AND winner_team_id IS NULL
          AND team_a_id IS NOT NULL AND team_b_id IS NOT NULL
        """,
        season, league_id,
    )

    resolved = []
    for node in pending:
        scores = await conn.fetch(
            "SELECT home_score, away_score FROM matchups WHERE playoff_bracket_matchup_id = $1",
            node["id"],
        )
        if len(scores) < weeks_per_matchup or any(r["home_score"] is None or r["away_score"] is None for r in scores):
            continue  # not every real week has a score in yet

        team_a_total = sum(r["home_score"] for r in scores)
        team_b_total = sum(r["away_score"] for r in scores)
        # A tie is real-world astronomically unlikely over an aggregate
        # of real fantasy scores, but not impossible — the better seed
        # (team_a, by construction: see generate_playoff_bracket's own
        # seed_a/seed_b pairing) wins it, a real disclosed tiebreak
        # rather than a silently-wrong or unhandled state.
        winner_id = node["team_a_id"] if team_a_total >= team_b_total else node["team_b_id"]

        async with conn.transaction():
            await conn.execute(
                "UPDATE playoff_bracket_matchups SET winner_team_id = $1 WHERE id = $2", winner_id, node["id"],
            )
            resolved.append({
                "id": node["id"], "round": node["round"], "slot": node["slot"], "winner_team_id": winner_id,
            })

            next_round = node["round"] + 1
            next_slot = node["slot"] // 2
            next_node = await conn.fetchrow(
                "SELECT id, team_a_id, team_b_id FROM playoff_bracket_matchups "
                "WHERE season = $1 AND league_id = $2 AND round = $3 AND slot = $4",
                season, league_id, next_round, next_slot,
            )
            if next_node is None:
                continue  # node["round"] was the final — nothing advances further

            column = "team_a_id" if node["slot"] % 2 == 0 else "team_b_id"
            await conn.execute(
                f"UPDATE playoff_bracket_matchups SET {column} = $1 WHERE id = $2", winner_id, next_node["id"],
            )

            other_team_id = next_node["team_b_id"] if column == "team_a_id" else next_node["team_a_id"]
            if other_team_id is not None:
                # Both feeders of next_node are now known — its real
                # per-week matchups can finally be written. start_week
                # is computed fresh (not stored per-round) since it's a
                # pure function of the season's own start_week/
                # weeks_per_matchup and this round number.
                start_week = settings["start_week"] or await _infer_start_week(conn, season, league_id)
                round_start_week = start_week + (next_round - 1) * weeks_per_matchup
                team_a_id = winner_id if column == "team_a_id" else other_team_id
                team_b_id = other_team_id if column == "team_a_id" else winner_id
                await _create_matchup_weeks(
                    conn, season, league_id, next_node["id"], team_a_id, team_b_id,
                    round_start_week, weeks_per_matchup,
                )

    return resolved


async def get_bracket_view(conn, season: int, league_id: int = DEFAULT_LEAGUE_ID) -> list[dict]:
    """Read-only display shape for the bracket — team names (not just
    ids) and each node's real aggregate score so far (summed across
    however many of its weeks_per_matchup weeks are already scored),
    for a frontend bracket view. Empty list before generate_playoff_
    bracket has ever run for this season."""
    rows = await conn.fetch(
        """
        SELECT b.id, b.round, b.slot,
               b.team_a_id, ta.team_name AS team_a_name, b.team_a_seed,
               b.team_b_id, tb.team_name AS team_b_name, b.team_b_seed,
               b.winner_team_id, tw.team_name AS winner_team_name,
               s.team_a_score, s.team_b_score, s.weeks_played
        FROM playoff_bracket_matchups b
        LEFT JOIN teams_by_season ta ON ta.id = b.team_a_id
        LEFT JOIN teams_by_season tb ON tb.id = b.team_b_id
        LEFT JOIN teams_by_season tw ON tw.id = b.winner_team_id
        LEFT JOIN LATERAL (
            SELECT SUM(m.home_score) AS team_a_score, SUM(m.away_score) AS team_b_score, COUNT(*) AS weeks_played
            FROM matchups m WHERE m.playoff_bracket_matchup_id = b.id
        ) s ON TRUE
        WHERE b.season = $1 AND b.league_id = $2
        ORDER BY b.round, b.slot
        """,
        season, league_id,
    )
    return [dict(r) for r in rows]
