"""
Real in-app regular-season schedule generator — the other half of the
competitive audit's #2 confirmed structural gap (2026-09), alongside
app/domain/playoffs.py's bracket engine. Matchup pairing has never
actually been generated by this app; it's read from a live, separate
ESPN league via the same private, unofficial `espn_api` library the
draft/roster/lineup pivot was explicitly built to eliminate.

Unlike the playoff bracket, this can only ever apply going FORWARD —
the current real season's regular-season schedule is already ESPN-
synced and (by the time this shipped) partly played; a new generator
can't retroactively replace real games that already happened. This is
the tool a commissioner runs once, at the start of a season (right
after teams exist, typically right after the draft), to schedule that
season's real regular-season matchups in-app instead of syncing them
from ESPN.

Algorithm: the standard "circle method" round-robin — fixes one team
and rotates the rest each round, producing team_count - 1 rounds in
which every team plays every other team exactly once. A season with
more weeks than that cycles through the same rotation again (a real,
common pattern for a schedule longer than one full round-robin — e.g.
14 weeks for 12 teams repeats part of the first cycle), flipping home/
away each time a pairing repeats so the same team isn't always on the
road (or always at home) against the same opponent. Home/away is also
alternated within each individual round (not just across repeated
cycles) so the anchor team (team_ids[0], which the circle method never
rotates) isn't simply "always home" every single week — a known
cosmetic imperfection of the naive circle method that this cheaply
mitigates without a fully rigorous home/away-balancing algorithm,
matching this app's own "even a simple version is far better than
none" scoping standard elsewhere (see playoffs.py).

An odd team_count gets a bye every round (one team sits out) — real
and handled, just never written as a `matchups` row (there's no
opponent to pair with), so a bye week simply has one fewer game than
usual rather than a fabricated "vs BYE" row.
"""
from app.domain.schedule_exceptions import NotEnoughTeamsError, ScheduleAlreadyExistsError

_BYE = None


def generate_round_robin_pairings(team_ids: list[int], weeks: int) -> list[tuple[int, int, int]]:
    """Pure function, no DB — returns (week, home_team_id, away_team_id)
    tuples, week 1-indexed. Raises NotEnoughTeamsError for fewer than 2
    teams; a `weeks` of 0 or less just returns an empty schedule (not
    an error — a commissioner might legitimately want to preview a
    zero-length range)."""
    if len(team_ids) < 2:
        raise NotEnoughTeamsError(f"Need at least 2 teams to generate a schedule, got {len(team_ids)}")

    arr = list(team_ids)
    if len(arr) % 2 == 1:
        arr.append(_BYE)  # a placeholder — never written as a real matchup
    n = len(arr)
    rounds_per_cycle = n - 1

    base_rounds: list[list[tuple[int, int]]] = []
    for r in range(rounds_per_cycle):
        pairings = []
        for i in range(n // 2):
            a, b = arr[i], arr[n - 1 - i]
            if a is _BYE or b is _BYE:
                continue
            home, away = (a, b) if r % 2 == 0 else (b, a)
            pairings.append((home, away))
        base_rounds.append(pairings)
        arr = [arr[0]] + [arr[-1]] + arr[1:-1]  # circle-method rotation, arr[0] fixed

    schedule = []
    for week in range(1, weeks + 1):
        cycle = (week - 1) // rounds_per_cycle
        round_index = (week - 1) % rounds_per_cycle
        flip_for_repeat = cycle % 2 == 1
        for home, away in base_rounds[round_index]:
            if flip_for_repeat:
                home, away = away, home
            schedule.append((week, home, away))

    return schedule


async def generate_regular_season_schedule(conn, season: int, league_id: int, weeks: int) -> list[dict]:
    """Real write — fetches this season's real teams (teams_by_season),
    generates their pairings, and inserts them as `matchups` rows
    (is_playoff=FALSE), same table/shape ESPN sync has always written
    to. Refuses to run if any regular-season matchup already exists for
    this (season, league_id) — see ScheduleAlreadyExistsError."""
    existing = await conn.fetchval(
        "SELECT 1 FROM matchups WHERE season = $1 AND league_id = $2 AND is_playoff = FALSE LIMIT 1",
        season, league_id,
    )
    if existing:
        raise ScheduleAlreadyExistsError(f"A regular-season schedule already exists for season {season}")

    team_rows = await conn.fetch(
        "SELECT id FROM teams_by_season WHERE season = $1 AND league_id = $2 ORDER BY id", season, league_id,
    )
    team_ids = [r["id"] for r in team_rows]
    pairings = generate_round_robin_pairings(team_ids, weeks)

    created = []
    async with conn.transaction():
        for week, home_id, away_id in pairings:
            row_id = await conn.fetchval(
                """
                INSERT INTO matchups (season, week, home_team_id, away_team_id, is_playoff, league_id)
                VALUES ($1, $2, $3, $4, FALSE, $5)
                RETURNING id
                """,
                season, week, home_id, away_id, league_id,
            )
            created.append({"id": row_id, "week": week, "home_team_id": home_id, "away_team_id": away_id})

    return created
