"""add in-app playoff bracket engine tables and settings

Real playoff bracket generation (competitive audit's #2 confirmed
structural gap, 2026-09): the playoff bracket — and the regular-season
matchup schedule — have never actually been generated by this app.
Both are read from a live, separate ESPN league via the same private,
unofficial `espn_api` library the draft/roster/lineup pivot was
explicitly built to eliminate. `matchups.is_playoff` itself is set by
that ESPN sync (comparing week number to ESPN's own reported
`reg_season_count`), not computed in-app. If that shadow ESPN league
is ever abandoned or mismanaged, this app has no schedule and no
playoffs at all — an operational continuity risk to the app's own real
season, not just a competitive-feature gap.

This migration adds the playoff half of the fix (the regular-season
schedule generator is a separate, lower-urgency project for next
season's draft — this season's schedule is already ESPN-synced and
partly played, so a new generator can't retroactively replace it
anyway; playoffs are the piece with real near-term stakes).

- league_playoff_settings gains two columns this league's real ESPN
  settings actually specify (the commissioner's own screenshot,
  2026-09: "Playoff Teams: 4, Weeks Per Playoff Matchup: 2") but that
  were never persisted anywhere before this — only playoff_team_count
  existed. `weeks_per_matchup` defaults to 1 (a single-week matchup,
  the more common default across platforms) so any league that never
  touches this setting keeps today's implicit behavior; this league
  sets it to 2. `start_week` is nullable — when unset,
  app/domain/playoffs.py infers it from this season's own already-
  synced regular-season matchups (one week after the last real
  regular-season week), so a season that hasn't explicitly configured
  this yet still gets a sane default from real data already in the DB.

- playoff_bracket_matchups is the bracket TREE structure — round/slot/
  seed/winner — kept separate from `matchups` (which stays exactly
  what it's always been: one row per real head-to-head NFL week).
  A round's pairing can be known (and its `matchups` rows generated)
  the moment both feeding teams are determined; later rounds start
  with team_a_id/team_b_id NULL and get filled in once the earlier
  round's winner is computed, which is also the moment that round's
  own real per-week `matchups` rows get created.

- matchups.playoff_bracket_matchup_id links a real per-week playoff
  matchup back to its bracket node, so a multi-week (weeks_per_matchup
  &gt; 1) aggregate matchup can sum real per-week scores to find a
  winner without duplicating any of the existing scoring engine
  (app/domain/matchup_scoring.py, app/domain/weekly_stats.py) — those
  keep writing to `matchups.home_score`/`away_score` exactly as they
  do today; app/domain/playoffs.py only ever reads that.

Revision ID: 3c8416bb59e1
Revises: c7f1a9d3e5b2
Create Date: 2026-09-08 00:00:00.000000
"""
from typing import Sequence, Union

from alembic import op

revision: str = '3c8416bb59e1'
down_revision: Union[str, Sequence[str], None] = 'c7f1a9d3e5b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TABLE league_playoff_settings ADD COLUMN weeks_per_matchup INTEGER NOT NULL DEFAULT 1")
    op.execute("ALTER TABLE league_playoff_settings ADD COLUMN start_week INTEGER")

    op.execute(
        """
        CREATE TABLE playoff_bracket_matchups (
            id                  SERIAL PRIMARY KEY,
            season              INTEGER NOT NULL,
            league_id           INTEGER NOT NULL REFERENCES leagues(id),
            round               INTEGER NOT NULL,
            slot                INTEGER NOT NULL,
            team_a_id           INTEGER REFERENCES teams_by_season(id),
            team_a_seed         INTEGER,
            team_b_id           INTEGER REFERENCES teams_by_season(id),
            team_b_seed         INTEGER,
            winner_team_id      INTEGER REFERENCES teams_by_season(id),
            created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
            UNIQUE (season, league_id, round, slot)
        )
        """
    )
    op.execute("ALTER TABLE matchups ADD COLUMN playoff_bracket_matchup_id INTEGER REFERENCES playoff_bracket_matchups(id)")


def downgrade() -> None:
    op.execute("ALTER TABLE matchups DROP COLUMN playoff_bracket_matchup_id")
    op.execute("DROP TABLE playoff_bracket_matchups")
    op.execute("ALTER TABLE league_playoff_settings DROP COLUMN start_week")
    op.execute("ALTER TABLE league_playoff_settings DROP COLUMN weeks_per_matchup")
